# get_ruuter_services:
#   call: http.get
#   args:
#     url: http://node_server:3008/ruuter/list
#   result: results
get_services_list:
  call: http.post
  args:
    url: http://resql:8087/get-services-list
  result: results

return_ok:
  status: 200
  return: ${results.response.body}
  next: end
