version: '3.9'
services:
  ruuter:
    container_name: ruuter
    image: ruuter
    environment:
      - application.cors.allowedOrigins=http://localhost:3001
      - application.httpCodesAllowList=200,201,202,203,204,205,206,207,208,226
      - application.logging.displayRequestContent=true
      - application.logging.displayResponseContent=true
    volumes:
      - ./DSL/Ruuter:/DSL
    ports:
      - 8080:8080
    networks:
      - bykstack
  resql:
    container_name: resql
    image: resql
    depends_on:
      - database
    environment:
      - sqlms.datasources.[0].name=users
      - sqlms.datasources.[0].jdbcUrl=jdbc:postgresql://database:5432/users_db
      - sqlms.datasources.[0].username=byk
      - sqlms.datasources.[0].password=01234
      - sqlms.datasources.[1].name=services
      - sqlms.datasources.[1].jdbcUrl=jdbc:postgresql://database:5432/services_db
      - sqlms.datasources.[1].username=byk
      - sqlms.datasources.[1].password=01234
      - logging.level.org.springframework.boot=INFO
    ports:
      - 8082:8082
    volumes:
      - ./DSL/Resql/services:/workspace/app/templates/services
    networks:
      - bykstack
  database:
    container_name: database
    image: postgres:14.1
    environment:
      - POSTGRES_USER=byk
      - POSTGRES_PASSWORD=01234
      - POSTGRES_MULTIPLE_DATABASES=users_db,services_db
    ports:
      - 5433:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
    networks:
      - bykstack
  data_mapper:
    container_name: data_mapper
    image: datamapper-node
    volumes:
      - ./DSL/DMapper/hbs:/workspace/app/views/services
      - ./DSL/DMapper/js:/workspace/app/js/services
    ports:
      - 3000:3000
    networks:
      - bykstack
  node_server:
    container_name: node_server
    build:
      context: ./DSL/Node
      dockerfile: Dockerfile
    environment:
      - CONTENT_FOLDER=/data
    volumes:
      - ./DSL:/data
    ports:
      - 3003:3003
    networks:
      - bykstack
  gui_dev:
    container_name: gui_dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8080
      - PORT=3001
    build:
      context: ./GUI
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    volumes:
      - /app/node_modules
      - ./GUI:/app
    networks:
      - bykstack

networks:
  bykstack:
    name: bykstack
    driver: bridge
