version: '3.9'
services:
  ruuter:
    container_name: ruuter
    image: ruuter
    environment:
      - application.cors.allowedOrigins=http://localhost:3001
      - application.httpCodesAllowList=200,201,202,203,204,205,206,207,208,226
      - application.logging.displayRequestContent=true
      - application.logging.displayResponseContent=true
    volumes:
      - ./DSL/Ruuter:/DSL
    ports:
      - 8080:8080
    networks:
      - bykstack
  resql:
    container_name: resql
    image: resql
    depends_on:
      - database
    environment:
      - sqlms.datasources.[0].name=services
      - sqlms.datasources.[0].jdbcUrl=jdbc:postgresql://database:5432/services_db
      - sqlms.datasources.[0].username=byk
      - sqlms.datasources.[0].password=01234
      - logging.level.org.springframework.boot=INFO
    ports:
      - 8082:8082
    volumes:
      - ./DSL/Resql/services:/workspace/app/templates/services
    networks:
      - bykstack
  resql_users:
    container_name: resql-users
    image: resql
    depends_on:
      - database
    environment:
      - server.port=8083
      - sqlms.datasources.[0].name=users
      - sqlms.datasources.[0].jdbcUrl=jdbc:postgresql://database:5432/users_db
      - sqlms.datasources.[0].username=byk
      - sqlms.datasources.[0].password=01234
      - logging.level.org.springframework.boot=INFO
    ports:
      - 8083:8083
    volumes:
      - ./DSL/Resql/users:/workspace/app/templates/users
    networks:
      - bykstack
  database:
    container_name: database
    image: postgres:14.1
    environment:
      - POSTGRES_USER=byk
      - POSTGRES_PASSWORD=01234
      - POSTGRES_MULTIPLE_DATABASES=users_db,services_db
    ports:
      - 5433:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
    networks:
      - bykstack
  data_mapper:
    container_name: data_mapper
    image: datamapper-node
    volumes:
      - ./DSL/DMapper/hbs:/workspace/app/views/services
      - ./DSL/DMapper/js:/workspace/app/js/services
    ports:
      - 3000:3000
    networks:
      - bykstack
  node_server:
    container_name: node_server
    build:
      context: ./DSL/Node
      dockerfile: Dockerfile.dev
    environment:
      - CONTENT_FOLDER=/data
    volumes:
      - ./DSL:/data
      - ./DSL/Node:/app
    ports:
      - 3003:3003
    networks:
      - bykstack
  gui_dev:
    container_name: gui_dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8080
      - PORT=3001
    build:
      context: ./GUI
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    volumes:
      - /app/node_modules
      - ./GUI:/app
    networks:
      - bykstack
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - node.name=opensearch
      - discovery.seed_hosts=opensearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - bykstack

volumes:
  opensearch-data1:


networks:
  bykstack:
    name: bykstack
    driver: bridge
